# Generated by Django 6.0.1 on 2026-03-27 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "height",
                    models.FloatField(blank=True, help_text="Height in cm", null=True),
                ),
                (
                    "weight",
                    models.FloatField(blank=True, help_text="Weight in kg", null=True),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "dob",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "fcm_token",
                    models.CharField(
                        blank=True,
                        help_text="Firebase Device Token for Push Notifications",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "chronic_diseases",
                    models.TextField(
                        blank=True, help_text="Step 1: Chronic Diseases", null=True
                    ),
                ),
                (
                    "previous_surgeries",
                    models.TextField(
                        blank=True, help_text="Step 1: Previous Surgeries", null=True
                    ),
                ),
                (
                    "major_injuries",
                    models.TextField(
                        blank=True, help_text="Step 1: Major Injuries", null=True
                    ),
                ),
                (
                    "disabilities_genetic_conditions",
                    models.TextField(
                        blank=True,
                        help_text="Step 1: Disabilities or Genetic Conditions",
                        null=True,
                    ),
                ),
                (
                    "ongoing_treatments",
                    models.TextField(
                        blank=True, help_text="Step 2: Ongoing Treatments", null=True
                    ),
                ),
                (
                    "supplements",
                    models.TextField(
                        blank=True, help_text="Step 2: Supplements", null=True
                    ),
                ),
                (
                    "medication_allergies",
                    models.TextField(
                        blank=True, help_text="Step 2: Medication Allergies", null=True
                    ),
                ),
                (
                    "current_medications",
                    models.TextField(
                        blank=True, help_text="Step 2: Current Medications", null=True
                    ),
                ),
                (
                    "allergy_type",
                    models.CharField(
                        blank=True,
                        help_text="Step 3: Allergy Type",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "allergy_severity",
                    models.CharField(
                        blank=True,
                        help_text="Step 3: Severity",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "allergy_symptoms",
                    models.TextField(
                        blank=True, help_text="Step 3: Common Symptoms", null=True
                    ),
                ),
                (
                    "emergency_medication",
                    models.TextField(
                        blank=True, help_text="Step 3: Emergency Medication", null=True
                    ),
                ),
                (
                    "s3_additional_notes",
                    models.TextField(
                        blank=True, help_text="Step 3: Additional Notes", null=True
                    ),
                ),
                (
                    "family_chronic_diseases",
                    models.TextField(
                        blank=True,
                        help_text="Step 4: Chronic Diseases in Family",
                        null=True,
                    ),
                ),
                (
                    "family_genetic_disorders",
                    models.TextField(
                        blank=True, help_text="Step 4: Genetic Disorders", null=True
                    ),
                ),
                (
                    "family_members_health",
                    models.TextField(
                        blank=True,
                        help_text="Step 4: Family Members' Health",
                        null=True,
                    ),
                ),
                (
                    "s4_additional_notes",
                    models.TextField(
                        blank=True, help_text="Step 4: Additional Notes", null=True
                    ),
                ),
                (
                    "physical_activity_level",
                    models.CharField(
                        blank=True,
                        help_text="Step 5: Physical Activity Level",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "diet_type",
                    models.CharField(
                        blank=True,
                        help_text="Step 5: Diet Type",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "average_sleep_hours",
                    models.FloatField(
                        blank=True, help_text="Step 5: Average Sleep Hours", null=True
                    ),
                ),
                (
                    "smoking_habits",
                    models.CharField(
                        blank=True,
                        help_text="Step 5: Smoking Habits",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "s5_additional_notes",
                    models.TextField(
                        blank=True, help_text="Step 5: Additional Notes", null=True
                    ),
                ),
                (
                    "overall_health_evaluation",
                    models.CharField(
                        blank=True,
                        help_text="Step 6: Overall Health Evaluation",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "current_symptoms",
                    models.TextField(
                        blank=True, help_text="Step 6: Current Symptoms", null=True
                    ),
                ),
                (
                    "daily_energy_level",
                    models.CharField(
                        blank=True,
                        help_text="Step 6: Daily Energy Level",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "sleep_quality",
                    models.CharField(
                        blank=True,
                        help_text="Step 6: Sleep Quality",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "physical_limitations",
                    models.TextField(
                        blank=True, help_text="Step 6: Physical Limitations", null=True
                    ),
                ),
                (
                    "s6_additional_notes",
                    models.TextField(
                        blank=True, help_text="Step 6: Additional Notes", null=True
                    ),
                ),
                (
                    "general_mood",
                    models.CharField(
                        blank=True,
                        help_text="Step 7: General Mood",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "stress_level",
                    models.CharField(
                        blank=True,
                        help_text="Step 7: Stress Level",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "emotional_support",
                    models.CharField(
                        blank=True,
                        help_text="Step 7: Emotional Support Availability",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "psychological_consultations",
                    models.TextField(
                        blank=True,
                        help_text="Step 7: Previous Psychological Consultations",
                        null=True,
                    ),
                ),
                (
                    "s7_additional_notes",
                    models.TextField(
                        blank=True, help_text="Step 7: Additional Notes", null=True
                    ),
                ),
                (
                    "vaccines_received",
                    models.TextField(
                        blank=True, help_text="Step 8: Vaccines Received", null=True
                    ),
                ),
                (
                    "vaccine_date_administered",
                    models.TextField(
                        blank=True,
                        help_text="Step 8: Date Administered (List)",
                        null=True,
                    ),
                ),
                (
                    "missed_vaccines",
                    models.TextField(
                        blank=True, help_text="Step 8: Missed Vaccines", null=True
                    ),
                ),
                (
                    "vaccine_side_effects",
                    models.TextField(
                        blank=True, help_text="Step 8: Notable Side Effects", null=True
                    ),
                ),
                (
                    "s8_additional_notes",
                    models.TextField(
                        blank=True, help_text="Step 8: Additional Notes", null=True
                    ),
                ),
                (
                    "last_dental_checkup",
                    models.DateField(
                        blank=True, help_text="Step 9: Last Dental Checkup", null=True
                    ),
                ),
                (
                    "last_general_checkup",
                    models.DateField(
                        blank=True, help_text="Step 9: Last General Checkup", null=True
                    ),
                ),
                (
                    "last_blood_test",
                    models.DateField(
                        blank=True, help_text="Step 9: Last Blood Test", null=True
                    ),
                ),
                (
                    "last_eye_examination",
                    models.DateField(
                        blank=True, help_text="Step 9: Last Eye Examination", null=True
                    ),
                ),
                (
                    "doctors_notes",
                    models.TextField(
                        blank=True,
                        help_text="Step 9: Doctor's Notes or Recommendations",
                        null=True,
                    ),
                ),
                (
                    "s9_additional_notes",
                    models.TextField(
                        blank=True, help_text="Step 9: Additional Notes", null=True
                    ),
                ),
                (
                    "clinician_access",
                    models.BooleanField(
                        default=False,
                        help_text="Allow health reports to be shared securely with a clinician",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
