# Generated by Django 6.0.2 on 2026-03-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_medicalprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprofile',
            name='allergy_severity',
            field=models.CharField(blank=True, help_text='Step 3: Severity', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='allergy_symptoms',
            field=models.TextField(blank=True, help_text='Step 3: Common Symptoms', null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='allergy_type',
            field=models.CharField(blank=True, help_text='Step 3: Allergy Type', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='average_sleep_hours',
            field=models.FloatField(blank=True, help_text='Step 5: Average Sleep Hours', null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='chronic_diseases',
            field=models.TextField(blank=True, help_text='Step 1: Chronic Diseases', null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='clincian_access',
            field=models.BooleanField(default=False, help_text='Allow health reports to be shared securely with a clinician'),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='current_medications',
            field=models.TextField(blank=True, help_text='Step 2: Current Medications', null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='current_symptoms',
            field=models.TextField(blank=True, help_text='Step 6: Current Symptoms', null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='daily_energy_level',
            field=models.CharField(blank=True, help_text='Step 6: Daily Energy Level', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='diet_type',
            field=models.CharField(blank=True, help_text='Step 5: Diet Type', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='disabilities_genetic_conditions',
            field=models.TextField(blank=True, help_text='Step 1: Disabilities or Genetic Conditions', null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='doctors_notes',
            field=models.TextField(blank=True, help_text="Step 9: Doctor's Notes or Recommendations", null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='emergency_medication',
            field=models.TextField(blank=True, help_text='Step 3: Emergency Medication', null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='emotional_support',
            field=models.CharField(blank=True, help_text='Step 7: Emotional Support Availability', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='family_chronic_diseases',
            field=models.TextField(blank=True, help_text='Step 4: Chronic Diseases in Family', null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='family_genetic_disorders',
            field=models.TextField(blank=True, help_text='Step 4: Genetic Disorders', null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='family_members_health',
            field=models.TextField(blank=True, help_text="Step 4: Family Members' Health", null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='Firebase Device Token for Push Notifications', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='general_mood',
            field=models.CharField(blank=True, help_text='Step 7: General Mood', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='last_blood_test',
            field=models.DateField(blank=True, help_text='Step 9: Last Blood Test', null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='last_dental_checkup',
            field=models.DateField(blank=True, help_text='Step 9: Last Dental Checkup', null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='last_eye_examination',
            field=models.DateField(blank=True, help_text='Step 9: Last Eye Examination', null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='last_general_checkup',
            field=models.DateField(blank=True, help_text='Step 9: Last General Checkup', null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='major_injuries',
            field=models.TextField(blank=True, help_text='Step 1: Major Injuries', null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='medication_allergies',
            field=models.TextField(blank=True, help_text='Step 2: Medication Allergies', null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='missed_vaccines',
            field=models.TextField(blank=True, help_text='Step 8: Missed Vaccines', null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='ongoing_treatments',
            field=models.TextField(blank=True, help_text='Step 2: Ongoing Treatments', null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='physical_activity_level',
            field=models.CharField(blank=True, help_text='Step 5: Physical Activity Level', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='physical_limitations',
            field=models.TextField(blank=True, help_text='Step 6: Physical Limitations', null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='previous_surgeries',
            field=models.TextField(blank=True, help_text='Step 1: Previous Surgeries', null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='psychological_consultations',
            field=models.TextField(blank=True, help_text='Step 7: Previous Psychological Consultations', null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='s3_additional_notes',
            field=models.TextField(blank=True, help_text='Step 3: Additional Notes', null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='s4_additional_notes',
            field=models.TextField(blank=True, help_text='Step 4: Additional Notes', null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='s5_additional_notes',
            field=models.TextField(blank=True, help_text='Step 5: Additional Notes', null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='s6_additional_notes',
            field=models.TextField(blank=True, help_text='Step 6: Additional Notes', null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='s7_additional_notes',
            field=models.TextField(blank=True, help_text='Step 7: Additional Notes', null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='s8_additional_notes',
            field=models.TextField(blank=True, help_text='Step 8: Additional Notes', null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='s9_additional_notes',
            field=models.TextField(blank=True, help_text='Step 9: Additional Notes', null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='sleep_quality',
            field=models.CharField(blank=True, help_text='Step 6: Sleep Quality', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='smoking_habits',
            field=models.CharField(blank=True, help_text='Step 5: Smoking Habits', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='stress_level',
            field=models.CharField(blank=True, help_text='Step 7: Stress Level', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='supplements',
            field=models.TextField(blank=True, help_text='Step 2: Supplements', null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='vaccine_date_administered',
            field=models.TextField(blank=True, help_text='Step 8: Date Administered (List)', null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='vaccine_side_effects',
            field=models.TextField(blank=True, help_text='Step 8: Notable Side Effects', null=True),
        ),
        migrations.AddField(
            model_name='medicalprofile',
            name='vaccines_received',
            field=models.TextField(blank=True, help_text='Step 8: Vaccines Received', null=True),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in cm', null=True),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kg', null=True),
        ),
    ]
